title: My Simple Weird Blog
description: Minimal blog structure from which to expand and customise 
markdown: kramdown
baseurl: "/simpleblog"
url: "https://yellowmoss.github.io/"
permalink: "/:year/:month/:day/:title"
